import{S as f,a as d,i as a}from"./assets/vendor-0LLe4tDC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const c=document.querySelector(".gallery"),u=document.querySelector(".loader");let m=new f(".gallery a",{captionsData:"alt",captionDelay:250});const g=s=>{const o=s.map(e=>`<li class="gallery-item">
                <a href="${e.largeImageURL}">
                  <img src="${e.webformatURL}" width='360' height='200' alt="${e.tags}">
                </a>
                
                <ul>
                    <li><b>Likes</b> ${e.likes}</li>
                    <li><b>Views</b> ${e.views}</li>
                    <li><b>Comments</b> ${e.comments}</li>
                    <li><b>Downloads</b> ${e.downloads}</li>
                </ul>
            </li>`).join("");c.insertAdjacentHTML("beforeend",o),m.refresh()},h=()=>{u.style.display="block"},p=()=>{u.style.display="none"},y=()=>{c.innerHTML=""},b="51088577-7b521529318281431558696f8",w=s=>{const o=`https://pixabay.com/api/?key=${b}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;d.get(o).then(e=>{if(!e.ok)throw new Error("Network response was not ok");if(e.data.hits.length>0)return e.data.hits;throw new Error("No images found")}).catch(e=>{throw console.error("Error fetching images:",e),e})},l=document.querySelector(".form");document.querySelector(".loader");l.addEventListener("submit",s=>{s.preventDefault(),y();const o=s.target.elements.search.value;if(o===""){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}h(),w(o).then(e=>{if(e.hits.length===0){a.warning({title:"No results",message:"No images found for your search query.",position:"topRight"});return}g(e.hits)}).catch(e=>{a.error({title:"Error",message:"There was an error fetching the images. Please try again later.",position:"topRight"}),console.error("Error fetching images:",e)}).finally(()=>{p()}),l.reset()});
//# sourceMappingURL=index.js.map
